<?php
if ( ! defined( 'ABSPATH' ) ) exit;
/**
 * File Name: dashboard.php
 * Plugin Name: DigitaleZen AntiSpam Shield for CF7
 * Author: DigitaleZen
 * License: GPLv2 or later
 */

// Sicurezza base
if (!current_user_can('manage_options')) return;

$log_email = get_option('dz_cf7_log_email', get_option('admin_email'));
$upload_dir = DZ_CF7_UPLOAD_DIR;
$upload_url = DZ_CF7_UPLOAD_URL;

$log_file = $upload_url . 'cf7-spam-log.csv';
$blacklist_file = $upload_url . 'cf7-blacklist.json';
?>

<div class="wrap" style="max-width: 800px;">
	<h1 style="margin-bottom: 0;">
            <?php echo esc_html__('🛡️ DigitaleZen AntiSpam Shield for CF7', 'digitalezen-antispam-shield-for-cf7'); ?>
	</h1>
	<p style="margin-top: 4px;">
            <?php echo esc_html__('Smart protection for Contact Form 7', 'digitalezen-antispam-shield-for-cf7'); ?>
	</p>

	<hr>

	<form method="POST">
	    <?php wp_nonce_field('dz_cf7_save_settings'); ?>

            <h2><?php esc_html_e('📬 Email report settings', 'digitalezen-antispam-shield-for-cf7'); ?></h2>
	    <p>
	        <?php
                echo esc_html__('Every Monday at 2:00 AM the report of blocked spam attempts will be sent.', 'digitalezen-antispam-shield-for-cf7');
	        ?>
	    </p>

	    <table class="form-table">
	        <tr>
	            <th scope="row">
	                <label for="dz_cf7_log_email">
                            <?php echo esc_html__('Destination email', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </label>
	            </th>
	            <td>
	                <input type="email" id="dz_cf7_log_email" name="dz_cf7_log_email"
	                       value="<?php echo esc_attr($log_email); ?>" class="regular-text">
	            </td>
	        </tr>
	    </table>

	    <p>
	        <input type="submit" name="dz_cf7_settings_submit" class="button button-primary"
                       value="<?php esc_attr_e('Save settings', 'digitalezen-antispam-shield-for-cf7'); ?>">
	    </p>
	</form>

	<hr>

        <h2><?php esc_html_e('🔧 Shortcodes to include in your CF7 forms', 'digitalezen-antispam-shield-for-cf7'); ?></h2>
	<ul style="margin-left: 1em;">
	    <li>
	        <code>[honeypot spamcheck]</code>
	        <a href="https://wordpress.org/plugins/contact-form-7-honeypot/" target="_blank" style="font-size: 0.9em; color: #0073aa; text-decoration: underline; margin-left: 6px;">
                <?php echo esc_html__('(Requires the Honeypot for Contact Form 7 plugin)', 'digitalezen-antispam-shield-for-cf7'); ?>
	        </a>
	    </li>
	    <li><code>[hidden timestamp default:get]</code></li>
	    <li><code>[hidden form-token default:get]</code></li>
	</ul>

	<hr>


        <h2><?php esc_html_e('📁 Files generated by the plugin', 'digitalezen-antispam-shield-for-cf7'); ?></h2>
	<table class="widefat striped" style="margin-bottom: 2em;">
	    <thead>
	        <tr>
	            <th><?php esc_html_e('File', 'digitalezen-antispam-shield-for-cf7'); ?></th>
                    <th><?php esc_html_e('Description', 'digitalezen-antispam-shield-for-cf7'); ?></th>
                    <th><?php esc_html_e('Actions', 'digitalezen-antispam-shield-for-cf7'); ?></th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td><code>cf7-spam-log.csv</code></td>
	            <td>
	                <?php
	                echo esc_html__('Log of blocked attempts (date, email, IP, reason, trigger)', 'digitalezen-antispam-shield-for-cf7');
	                ?>
	            </td>
	            <td>
	                <a href="<?php echo esc_url($log_file); ?>" class="button button-secondary" download>
	                    📥 <?php esc_html_e('Download', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
	            </td>
	        </tr>
	        <tr>
	            <td><code>cf7-blacklist.json</code></td>
	            <td>
	                <?php
	                echo esc_html__('Blacklist updated from Apps Script (IP, email, domains, etc.)', 'digitalezen-antispam-shield-for-cf7');
	                ?>
	            </td>
	            <td>
	                <a
	                    href="<?php
                                echo esc_url(
                                    wp_nonce_url(
                                        admin_url(
                                            'admin-ajax.php?action=dz_cf7_view_json&f=cf7-blacklist.json'
                                        ),
                                        'dz_cf7_view_json'
                                    )
                                );
	                    ?>"
	                    class="button button-secondary" target="_blank">
                            👁️ <?php esc_html_e('View', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
	                <a href="<?php echo esc_url($blacklist_file); ?>" class="button" download>
	                    📥 <?php esc_html_e('Download', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
	            </td>
	        </tr>
	        <tr>
	            <td><code>block-ip.txt</code></td>
	            <td>
	                <?php
	                echo esc_html__('Temporarily blocked IPs (soft block, 10 minutes)', 'digitalezen-antispam-shield-for-cf7');
	                ?>
	            </td>
	            <td>
                        <a
                            href="<?php echo esc_url(DZ_CF7_UPLOAD_URL . 'block-ip.txt'); ?>"
                            class="button button-secondary" target="_blank">
                            👁️ <?php esc_html_e('View', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
                        <a href="<?php echo esc_url(DZ_CF7_UPLOAD_URL . 'block-ip.txt'); ?>" class="button" download>
	                    📥 <?php esc_html_e('Download', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
	            </td>
	        </tr>
	        <tr>
	            <td><code>ip-attempts.json</code></td>
	            <td>
                    <?php echo esc_html__('Spam attempt history by IP', 'digitalezen-antispam-shield-for-cf7'); ?>
	            </td>
	            <td>
	                <a
	                    href="<?php
                                echo esc_url(
                                    wp_nonce_url(
                                        admin_url(
                                            'admin-ajax.php?action=dz_cf7_view_json&f=ip-attempts.json'
                                        ),
                                        'dz_cf7_view_json'
                                    )
                                );
	                    ?>"
	                    class="button button-secondary" target="_blank">
                            👁️ <?php esc_html_e('View', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
                        <a href="<?php echo esc_url(DZ_CF7_UPLOAD_URL . 'ip-attempts.json'); ?>" class="button" download>
	                    📥 <?php esc_html_e('Download', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
	            </td>
	        </tr>
	        <tr>
	            <td><code>email-attempts.json</code></td>
	            <td>
                    <?php echo esc_html__('Spam attempt history by email', 'digitalezen-antispam-shield-for-cf7'); ?>
	            </td>
	            <td>
	                <a
	                    href="<?php
                                echo esc_url(
                                    wp_nonce_url(
                                        admin_url(
                                            'admin-ajax.php?action=dz_cf7_view_json&f=email-attempts.json'
                                        ),
                                        'dz_cf7_view_json'
                                    )
                                );
	                    ?>"
	                    class="button button-secondary" target="_blank">
                            👁️ <?php esc_html_e('View', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
                        <a href="<?php echo esc_url(DZ_CF7_UPLOAD_URL . 'email-attempts.json'); ?>" class="button" download>
	                    📥 <?php esc_html_e('Download', 'digitalezen-antispam-shield-for-cf7'); ?>
	                </a>
	            </td>
	        </tr>
	    </tbody>
	</table>


	<hr>

        <h2><?php esc_html_e('📊 Blocked spam report (real data)', 'digitalezen-antispam-shield-for-cf7'); ?></h2>

	<canvas id="dz-cf7-chart" height="100" style="margin-bottom: 2em; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); border: 1px solid #ddd;"></canvas>

	<?php
	// Funzione aggiornata: conta per tipo e intervallo
	function dz_cf7_count_spam_by_type_and_range($minutes) {
            $path = DZ_CF7_UPLOAD_DIR . 'cf7-spam-log.csv';
	    if (!file_exists($path)) return [];

	    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
	    $now = time();
	    $types = [];

	    foreach ($lines as $line) {
	        $cols = str_getcsv($line);
	        if (count($cols) < 4) continue;

	        $ts = strtotime($cols[0]);
	        $motivo = trim($cols[3]);

	        if (($now - $ts) <= ($minutes * 60)) {
	            if (!isset($types[$motivo])) $types[$motivo] = 0;
	            $types[$motivo]++;
	        }
	    }

	    return $types;
	}

	// Intervalli temporali
        $intervalli = [
            '24h'      => 1440,
            '7 days'   => 10080,
            '28 days'  => 40320,
            '3 months' => 129600,
            '1 year'   => 525600
        ];

	$data_report_by_type = [];

	foreach ($intervalli as $label => $minutes) {
	    $data_report_by_type[$label] = dz_cf7_count_spam_by_type_and_range($minutes);
	}

        // Passa i dati al grafico JS
        wp_add_inline_script(
            'dz-cf7-dashboard',
            'window.dz_cf7_chart_grouped_data = ' . wp_json_encode($data_report_by_type) . ';',
            'before'
        );
        wp_add_inline_script(
            'dz-cf7-dashboard',
            'window.dz_cf7_chart_labels = ' . wp_json_encode(array_keys($intervalli)) . ';',
            'before'
        );

	?>


        <h3><?php esc_html_e('🧾 Latest blocked attempts', 'digitalezen-antispam-shield-for-cf7'); ?></h3>
	<table class="widefat striped" style="max-width: 100%; margin-top: 1em;">
	    <thead>
	        <tr>
                    <th><?php esc_html_e('Date', 'digitalezen-antispam-shield-for-cf7'); ?></th>
	            <th><?php esc_html_e('Email', 'digitalezen-antispam-shield-for-cf7'); ?></th>
	            <th><?php esc_html_e('IP', 'digitalezen-antispam-shield-for-cf7'); ?></th>
                    <th><?php esc_html_e('Reason', 'digitalezen-antispam-shield-for-cf7'); ?></th>
	            <th><?php esc_html_e('Trigger', 'digitalezen-antispam-shield-for-cf7'); ?></th>
	        </tr>
	    </thead>
	    <tbody>
	    <?php
        $path = DZ_CF7_UPLOAD_DIR . 'cf7-spam-log.csv';
	    if (file_exists($path)) {
	        $lines = array_reverse(file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES));
	        $max = 30;
	        foreach (array_slice($lines, 0, $max) as $line) {
	            $cols = str_getcsv($line);
	            echo '<tr>';
	            foreach ($cols as $col) {
	                echo '<td>' . esc_html($col) . '</td>';
	            }
	            echo '</tr>';
	        }
	    }
	    ?>
	    </tbody>
	</table>


	<hr>

	<p style="margin-top: 2em; text-align: center; color: #666;">
	    <small>
	        <?php
                echo wp_kses_post(
                    __('Powered by <a href="https://digitalezen.it" target="_blank" style="text-decoration: none;">DigitaleZen.it</a> 🚀', 'digitalezen-antispam-shield-for-cf7')
                );
	        ?>
	    </small>
	</p>


</div>
