name: CI - PHPCS & PHPUnit (no Composer)

on:
  push:
  pull_request:
  workflow_dispatch:  # pulsante "Run workflow"

jobs:
  phpcs:
    name: PHPCS (WordPress)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install PHPCS + WPCS deps (PHPCS 3.x compat)
        run: |
          set -e
          curl -Ls https://github.com/squizlabs/PHP_CodeSniffer/releases/latest/download/phpcs.phar -o phpcs.phar

          EXTRA_DIR="$RUNNER_TEMP/PHPCSExtra"
          UTILS_DIR="$RUNNER_TEMP/PHPCSUtils"
          WPCS_DIR="$RUNNER_TEMP/wpcs"

          git clone --depth=1 --branch 1.2.1 https://github.com/PHPCSStandards/PHPCSExtra.git "$EXTRA_DIR"
          git clone --depth=1 https://github.com/PHPCSStandards/PHPCSUtils.git "$UTILS_DIR"
          git clone --depth=1 https://github.com/WordPress/WordPress-Coding-Standards.git "$WPCS_DIR"

          php phpcs.phar --config-set installed_paths "$EXTRA_DIR,$UTILS_DIR,$WPCS_DIR"
          php phpcs.phar -i

      - name: Run PHPCS
        run: |
          set -e
          if [ -f phpcs.xml ] || [ -f phpcs.xml.dist ]; then
            # usa la tua configurazione; ignora i soli warning ai fini dell'exit code
            php phpcs.phar -p --report=summary --runtime-set ignore_warnings_on_exit 1 .
          else
            # fallback standard WordPress se non hai un phpcs.xml
            php phpcs.phar -p --standard=WordPress --extensions=php \
              --ignore=vendor/*,node_modules/*,assets/*,tests/*,.github/* \
              --report=summary .
          fi

  phpunit:
    name: PHPUnit (WordPress Test Suite)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    env:
      WP_TESTS_DB_NAME: wordpress_test
      WP_TESTS_DB_USER: root
      WP_TESTS_DB_PASS: root
      WP_TESTS_DB_HOST: 127.0.0.1
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysqli
          coverage: none
          tools: phpunit:9.6
      - name: Install SVN (serve allo script install-wp-tests)
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion
      - name: Prepare DB (drop & create to avoid prompts)
        run: |
          mysql -h 127.0.0.1 -uroot -proot -e 'DROP DATABASE IF EXISTS wordpress_test; CREATE DATABASE wordpress_test;'
      - name: Download & install WP test suite
        run: |
          curl -Ls https://raw.githubusercontent.com/wp-cli/scaffold-command/master/templates/install-wp-tests.sh -o /tmp/install-wp-tests.sh
          chmod +x /tmp/install-wp-tests.sh
          # ultimo parametro "true" = salta la creazione DB (già fatta sopra)
          bash /tmp/install-wp-tests.sh "$WP_TESTS_DB_NAME" "$WP_TESTS_DB_USER" "$WP_TESTS_DB_PASS" "$WP_TESTS_DB_HOST" latest true
      - name: Run PHPUnit
        run: phpunit -v
