  phpcs:
    name: PHPCS (WordPress)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Install PHPCS + WPCS deps
        run: |
          curl -Ls https://github.com/squizlabs/PHP_CodeSniffer/releases/latest/download/phpcs.phar -o phpcs.phar
          git clone --depth=1 https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          git clone --depth=1 https://github.com/PHPCSStandards/PHPCSUtils.git PHPCSUtils
          git clone --depth=1 https://github.com/PHPCSStandards/PHPCSExtra.git PHPCSExtra
          php phpcs.phar --config-set installed_paths "$GITHUB_WORKSPACE/PHPCSExtra,$GITHUB_WORKSPACE/PHPCSUtils,$GITHUB_WORKSPACE/wpcs"
          php phpcs.phar -i
      - name: Run PHPCS
        run: |
          if [ -f phpcs.xml ] || [ -f phpcs.xml.dist ]; then
            php phpcs.phar --report=summary .
          else
            php phpcs.phar --standard=WordPress --extensions=php --ignore=vendor/*,node_modules/*,assets/* --report=summary .
          fi
