name: CI - PHPCS & PHPUnit (no Composer)

on:
  push:
  pull_request:

jobs:
  phpcs:
    name: PHPCS (WordPress)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Install PHPCS + WPCS deps
        run: |
          curl -Ls https://github.com/squizlabs/PHP_CodeSniffer/releases/latest/download/phpcs.phar -o phpcs.phar
          git clone --depth=1 https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          git clone --depth=1 https://github.com/PHPCSStandards/PHPCSUtils.git PHPCSUtils
          git clone --depth=1 https://github.com/PHPCSStandards/PHPCSExtra.git PHPCSExtra
          php phpcs.phar --config-set installed_paths "$GITHUB_WORKSPACE/PHPCSExtra,$GITHUB_WORKSPACE/PHPCSUtils,$GITHUB_WORKSPACE/wpcs"
          php phpcs.phar -i
      - name: Run PHPCS
        run: |
          if [ -f phpcs.xml ] || [ -f phpcs.xml.dist ]; then
            php phpcs.phar --report=summary .
          else
            php phpcs.phar --standard=WordPress --extensions=php --ignore=vendor/*,node_modules/*,assets/* --report=summary .
          fi

  phpunit:
    name: PHPUnit (WordPress Test Suite)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports: ['3306:3306']
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      WP_TESTS_DB_NAME: wordpress_test
      WP_TESTS_DB_USER: root
      WP_TESTS_DB_PASS: root
      WP_TESTS_DB_HOST: 127.0.0.1
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit:9.6
      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion
      - name: Download & install WP test suite
        run: |
          curl -Ls https://raw.githubusercontent.com/wp-cli/scaffold-command/master/templates/install-wp-tests.sh -o /tmp/install-wp-tests.sh
          chmod +x /tmp/install-wp-tests.sh
          bash /tmp/install-wp-tests.sh $WP_TESTS_DB_NAME $WP_TESTS_DB_USER $WP_TESTS_DB_PASS $WP_TESTS_DB_HOST latest
      - name: Run PHPUnit
        run: phpunit
